services:
  mcsd:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: mcsd-dev
    privileged: true
    cgroup: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "8080:8080"